# Generated by Django 5.0.4 on 2024-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
